// <auto-generated />
namespace Framework.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeCompanyNameLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeCompanyNameLength));
        
        string IMigrationMetadata.Id
        {
            get { return "202111021639008_changeCompanyNameLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
